project:
  type: website
  preview: 
    port: 3333

execute:
  freeze: auto

website:
  title: "Quarto websites"
  description: "Materials for two-day short course on making Quarto websites"
  site-url: "https://andrewheiss.github.io/quarto-websites_2025-10/"
  # favicon: 

  repo-url: "https://github.com/andrewheiss/quarto-websites_2025-10"
  repo-actions: [source, issue]

  navbar:
    background: primary
    right:
      - icon: github
        href: https://github.com/andrewheiss/quarto-websites_2025-10

  sidebar:
    title: "Quarto Websites"
    style: docked
    background: secondary

    contents:
      - href: index.qmd
        text: Home

      - href: materials/00-setup/index.qmd
        text: Setup

      - section: "Materials"
        contents:
        - href: materials/01-intro/index.qmd
          text: Intro to Quarto

        - href: materials/basic-websites/index.qmd
          text: Creating basic websites

        - href: materials/advanced-websites/index.qmd
          text: Advanced website features

        - href: materials/publishing/index.qmd
          text: Publishing

        - href: materials/brand/index.qmd
          text: Customization and branding

        - href: materials/interactivity/index.qmd
          text: Interactivity

  page-footer:
    border: false
    background: "#dddddd"
    left: |
      Content {{< fa brands creative-commons >}} 2025 by [Andrew Heiss](https://www.andrewheiss.com) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}}
      [Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)](hhttps://creativecommons.org/licenses/by-sa/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub](https://github.com/andrewheiss/quarto-websites_2025-10)


format:
  html:
    theme:
      - cosmo
      - styles.scss
      - brand
    toc: true
