---
title: "Create an Online Presence with Quarto Websites"
subtitle: "Code Horizons Short Course"
date: "2025-10-17"
date-format: "MMMM [16-]DD, YYYY"
language:
  title-block-published: Workshop dates
---

## Overview

Creating and maintaining an online presence is essential for anyone who works with data. Whether you're a researcher, educator, or analyst, a well-crafted website can serve as your digital calling card, allowing you to showcase your work, share your insights and discoveries, and engage with the broader data analysis community. But building a website from scratch can feel overwhelming, especially if you lack web development experience. Enter [Quarto](https://quarto.org/): an open-source publishing tool that makes it easy to create beautiful, accessible, and feature-rich websites using just a few lines of Markdown—no HTML or CSS expertise required!

In this course, you'll learn how to use Quarto to build a variety of data-focused websites, from personal portfolios and blogs to project-specific sites, [research compendiums](https://research-compendium.science/), and interactive dashboards. You’ll also discover how to customize your site’s design, incorporate computational content from R, Python, and Observable JS, and create interactive elements like live code and data visualizations.

## Schedule

All times are US Eastern (New York) time:

```{r}
#| label: schedule-table
#| warning: false
#| message: false
#| echo: false

library(tinytable)
library(dplyr)
library(glue)

# To keep {tinytable} happy
set.seed(1234)

# fmt: skip
schedule <- tribble(
  ~Day,                 ~Time,         ~Title,                       ~Link,
  "Day 1 (October 16)", "10:30–11:30", "Welcome + Intro to Quarto",  "/materials/01-intro/",
  "Day 1 (October 16)", "11:30–12:30", "Creating basic websites",    "/materials/basic-websites/",
  "Day 1 (October 16)", "12:30–13:00", "*Break*",                    NA,
  "Day 1 (October 16)", "13:00–15:00", "Advanced website features",  "/materials/advanced-websites/",
  "Day 2 (October 17)", "10:30–11:00", "Publishing",                 "/materials/publishing/",
  "Day 2 (October 17)", "11:00–12:30", "Customization and branding", "/materials/brand/",
  "Day 2 (October 17)", "12:30–13:00", "*Break*",                    NA,
  "Day 2 (October 17)", "13:00–15:00", "Interactivity",              "/materials/interactivity/"
) |> 
  mutate(Content = ifelse(is.na(Link), Title, glue('[{Title}]({Link}){{target="_blank"}}')))

schedule |>
  select(Time, Content) |>
  tt(width = c(0.2, 0.8), colnames = FALSE) |>
  theme_empty() |>
  group_tt(i = schedule$Day) |>
  style_tt(i = "groupi", align = "l", bold = TRUE, background = "#dddddd") |>
  style_tt(i = "~groupi", j = 1, indent = 1) |>
  format_tt(j = 2, markdown = TRUE) |>
  theme_html(engine = "bootstrap", class = "table table-sm")
```

## Instructor

[Andrew Heiss](https://www.andrewheiss.com/) is an assistant professor in the Department of Public Management and Policy at the Andrew Young School of Policy Studies at Georgia State University. His research explores human rights and international nonprofit management, and focuses on authoritarian regulation of civil society and INGO responses to administrative crackdown. Heiss also studies and teaches quantitative research methods, causal inference, data visualization, and Bayesian analysis. He is an RStudio Certified Instructor whose work has appeared in journals such as the *Journal of Politics*, *Nonprofit and Voluntary Sector Quarterly*, the *Journal of Statistical Software*, the *Journal of Human Rights*, and *International Interactions*.
