---
title: "Setup"
format: html
---

To follow along with the course exercises, you'll need Quarto version 1.8+ and access to a code editor that supports R.

While Quarto itself doesn't require a programming language, the exercises will include code chunks in R. If you don’t already have R set up locally, I recommend using a cloud-based option like Posit Cloud.

## Recommended setup options

### Option 1: Posit Cloud (RStudio in the cloud)

- Create a free account at <https://posit.cloud/>
- Join the Posit Cloud workspace: <https://posit.cloud/spaces/704423/join?access_code=fDGrujjY7mb1j-9bq-dlKl7JZw5XkLdq5sm3cFoE>
- Click "Yes" to join the space.
- Click Content and select `quarto-websites-exercise-intro_2025-10` or go to `LINK FORTHCOMING`
- To save a copy of the project to your workspace, click "Save a permanent copy".

### Option 2: Local installation

Choose one editor and follow the steps:

::: {.panel-tabset}

#### RStudio

- Download and install RStudio: <https://posit.co/downloads/>
  - Make sure RStudio is version 2022.07+.
- Quarto comes pre-installed.
  - Make sure Quarto is version 1.8+.

#### Positron

- Download and install Positron: <https://positron.posit.co/download.html>
- Quarto comes pre-installed.
  - Make sure Quarto is version 1.8+.

#### VS Code

- Download and install VS Code: <https://code.visualstudio.com/download/>
- Download and install Quarto: <https://quarto.org/docs/get-started/>
- Install the following extensions:
  - Quarto Extension: <https://marketplace.visualstudio.com/items?itemName=quarto.quarto/>
  - Jupyter Extension: <https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter/> 
:::

## Accessing the course materials

If you are using a cloud-based option, the files will be included in the respecitve project folders.

If you are not using a cloud-based option:

**If you don’t use Git/GitHub:**

- Go to the GitHub repos for each example project:
  - <https://github.com/andrewheiss/quarto-websites-exercise-intro_2025-10>
  - <https://github.com/andrewheiss/quarto-websites-exercise-site_2025-10>
- Click the green "Code" button → "Download ZIP".
- Unzip the folder and open it in your chosen editor.

**If you use Git/GitHub:**

- Exercises are available here:
  - <https://github.com/andrewheiss/quarto-websites-exercise-intro_2025-10>
  - <https://github.com/andrewheiss/quarto-websites-exercise-site_2025-10>
- Clone each repository with Git:

  ```bash
  git clone https://github.com/andrewheiss/quarto-websites-exercise-intro_2025-10.git
  git clone https://github.com/andrewheiss/quarto-websites-exercise-site_2025-10.git
  ```

## Install the necessary R packages

If you are using Posit Cloud, the packages will be pre-installed. 

If you are using RStudio or Positron locally, install all the packages we'll use with:

```{.r}
install.packages(
  c("tidyverse", "quarto", "patchwork", "ggridges", "tinytable", "brand.yml"),
  repos = c('https://posit-dev.r-universe.dev', 'https://cloud.r-project.org')
)
```

## Create publishing accounts

For [the section on publishing](/materials/publishing/index.qmd), you'll neeed to create two free accounts (if you don't have them already):

- [Quarto Pub](https://quartopub.com/)
- [GitHub](https://github.com/)

## Credits {.appendix}

These instructions were adapted from Isabella Velásquez and Sara Altman's [posit::conf(2025) workshop](https://posit-conf-2025.github.io/quarto-brand/) on branded Quarto documents ([{{< fa brands github >}} GitHub repository](https://github.com/posit-conf-2025/quarto-brand)). They graciously licensed their content under [{{< fa brands creative-commons >}} Creative Commons CC-BY-SA {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}}](https://github.com/posit-conf-2025/quarto-brand/blob/main/LICENSE.md).
